services:
  - type: web
    name: fastapi-webpage-pdf
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash ./start.sh && uvicorn app:app --host 0.0.0.0 --port 10000"
    plan: free
